In [1]:
import pandas as pd

all_island = pd.read_csv("../data/all_island_quarterly_inflation.csv")
roi_clean = pd.read_csv("../data/roi_quarterly_clean.csv")

In [2]:
ni_keywords = [
    "Antrim", "Ards", "Armagh", "Belfast", "Causeway",
    "Derry", "Fermanagh", "Lisburn", "Mid", "Newry"
]

def is_ni(county):
    return any(k.lower() in county.lower() for k in ni_keywords)

all_island["is_ni"] = all_island["County"].apply(is_ni)

In [3]:
roi_existing = all_island[~all_island["is_ni"]].copy()
ni_existing  = all_island[all_island["is_ni"]].copy()

In [4]:
roi_updated = (
    roi_existing
    .drop(columns=["transaction_count", "avg_price"])
    .merge(
        roi_clean[[
            "County", "Year", "Quarter", "Period",
            "transaction_count", "avg_price"
        ]],
        on=["County", "Year", "Quarter", "Period"],
        how="left"
    )
)

In [5]:
all_island_clean = pd.concat(
    [roi_updated, ni_existing.drop(columns=["is_ni"])],
    ignore_index=True
)

In [6]:
# No missing prices
assert all_island_clean["avg_price"].notna().all()

# No missing transaction counts
assert all_island_clean["transaction_count"].notna().all()

# Row count unchanged
assert len(all_island_clean) == len(all_island)

In [9]:
all_island_clean.tail(10)

,County,Year,Quarter,Period,Inflation_Rate,real_avg_price,Region,is_ni,transaction_count,avg_price
2347,"Newry, Mourne and Down",2023,2,2023 Q2,8.43,188264.62,Northern Ireland,NaN,399.0,204135.33
2348,"Newry, Mourne and Down",2023,3,2023 Q3,6.71,201034.72,Northern Ireland,NaN,410.0,214524.15
2349,"Newry, Mourne and Down",2023,4,2023 Q4,4.18,201310.57,Northern Ireland,NaN,438.0,209725.35
2350,"Newry, Mourne and Down",2024,1,2024 Q1,3.54,201836.61,Northern Ireland,NaN,341.0,208981.63
2351,"Newry, Mourne and Down",2024,2,2024 Q2,2.10,220334.13,Northern Ireland,NaN,374.0,224961.15
2352,"Newry, Mourne and Down",2024,3,2024 Q3,2.04,221888.85,Northern Ireland,NaN,501.0,226415.38
2353,"Newry, Mourne and Down",2024,4,2024 Q4,2.47,228088.96,Northern Ireland,NaN,528.0,233722.76
2354,"Newry, Mourne and Down",2025,1,2025 Q1,2.80,227906.48,Northern Ireland,NaN,457.0,234287.86
2355,"Newry, Mourne and Down",2025,2,2025 Q2,3.49,221496.68,Northern Ireland,NaN,312.0,229226.91
2356,"Newry, Mourne and Down",2025,3,2025 Q3,3.80,229974.12,Northern Ireland,NaN,443.0,238713.14

In [10]:
all_island_clean["is_ni"] = all_island_clean["Region"] == "Northern Ireland"

In [11]:
all_island_clean.tail(10)

,County,Year,Quarter,Period,Inflation_Rate,real_avg_price,Region,is_ni,transaction_count,avg_price
2347,"Newry, Mourne and Down",2023,2,2023 Q2,8.43,188264.62,Northern Ireland,True,399.0,204135.33
2348,"Newry, Mourne and Down",2023,3,2023 Q3,6.71,201034.72,Northern Ireland,True,410.0,214524.15
2349,"Newry, Mourne and Down",2023,4,2023 Q4,4.18,201310.57,Northern Ireland,True,438.0,209725.35
2350,"Newry, Mourne and Down",2024,1,2024 Q1,3.54,201836.61,Northern Ireland,True,341.0,208981.63
2351,"Newry, Mourne and Down",2024,2,2024 Q2,2.10,220334.13,Northern Ireland,True,374.0,224961.15
2352,"Newry, Mourne and Down",2024,3,2024 Q3,2.04,221888.85,Northern Ireland,True,501.0,226415.38
2353,"Newry, Mourne and Down",2024,4,2024 Q4,2.47,228088.96,Northern Ireland,True,528.0,233722.76
2354,"Newry, Mourne and Down",2025,1,2025 Q1,2.80,227906.48,Northern Ireland,True,457.0,234287.86
2355,"Newry, Mourne and Down",2025,2,2025 Q2,3.49,221496.68,Northern Ireland,True,312.0,229226.91
2356,"Newry, Mourne and Down",2025,3,2025 Q3,3.80,229974.12,Northern Ireland,True,443.0,238713.14

In [12]:
all_island_clean.head(10)

,County,Year,Quarter,Period,Inflation_Rate,real_avg_price,Region,is_ni,transaction_count,avg_price
0,Carlow,2010,1,2010 Q1,-3.37,177792.12,Republic of Ireland,False,23.0,171836.96
1,Carlow,2010,2,2010 Q2,-1.33,181996.35,Republic of Ireland,False,25.0,177037.00
2,Carlow,2010,3,2010 Q3,0.20,179568.78,Republic of Ireland,False,33.0,164772.73
3,Carlow,2010,4,2010 Q4,0.93,166736.86,Republic of Ireland,False,31.0,195185.81
4,Carlow,2011,1,2011 Q1,2.27,160972.85,Republic of Ireland,False,20.0,161475.00
5,Carlow,2011,2,2011 Q2,2.87,138161.47,Republic of Ireland,False,28.0,129868.75
6,Carlow,2011,3,2011 Q3,2.43,122479.54,Republic of Ireland,False,30.0,125825.00
7,Carlow,2011,4,2011 Q4,2.70,123048.62,Republic of Ireland,False,30.0,114411.83
8,Carlow,2012,1,2012 Q1,2.13,115122.82,Republic of Ireland,False,27.0,113648.15
9,Carlow,2012,2,2012 Q2,1.80,104048.10,Republic of Ireland,False,40.0,106701.98

In [14]:
all_island_clean.to_csv(
    "../data/all_island_quarterly_inflation_clean.csv",
    index=False
)