In [ ]:
# https://www.rateinflation.com/inflation-rate/uk-historical-inflation-rate/

import pandas as pd

data = {
    "Year": [2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010],
    "jan": [2.983, 3.981, 10.052, 5.456, 0.701, 1.769, 1.848, 2.989, 1.815, 0.293, 0.282, 1.889, 2.714, 3.576, 3.967, 3.476],
    "feb": [2.836, 3.411, 10.416, 6.177, 0.414, 1.710, 1.869, 2.708, 2.298, 0.284, 0.031, 1.724, 2.783, 3.435, 4.350, 2.966],
    "mar": [2.594, 3.228, 10.057, 7.023, 0.714, 1.523, 1.908, 2.458, 2.316, 0.462, -0.010, 1.606, 2.831, 3.461, 4.038, 3.384],
    "apr": [3.527, 2.333, 8.658, 9.011, 1.526, 0.767, 2.118, 2.382, 2.711, 0.287, -0.121, 1.773, 2.421, 3.044, 4.478, 3.731],
    "may": [3.358, 1.990, 8.681, 9.083, 2.115, 0.480, 2.021, 2.421, 2.875, 0.307, 0.111, 1.494, 2.700, 2.773, 4.453, 3.392],
    "jun": [3.576, 1.975, 7.950, 9.412, 2.514, 0.603, 2.005, 2.447, 2.644, 0.460, -0.040, 1.895, 2.919, 2.449, 4.201, 3.250],
    "jul": [3.829, 2.234, 6.827, 10.101, 2.040, 1.040, 2.061, 2.474, 2.629, 0.563, 0.146, 1.594, 2.765, 2.561, 4.431, 3.055],
    "aug": [3.788, 2.216, 6.657, 9.870, 3.197, 0.220, 1.724, 2.653, 2.861, 0.639, 0.008, 1.549, 2.690, 2.477, 4.507, 3.121],
    "sep": [3.783, 1.680, 6.652, 10.096, 3.080, 0.532, 1.715, 2.419, 2.959, 0.976, -0.125, 1.226, 2.672, 2.202, 5.178, 3.080],
    "oct": [3.559, 2.281, 4.600, 11.052, 4.206, 0.697, 1.464, 2.392, 3.001, 0.909, -0.111, 1.289, 2.191, 2.669, 4.982, 3.164],
    "nov": [None, 2.622, 3.941, 10.672, 5.130, 0.315, 1.474, 2.310, 3.092, 1.165, 0.111, 0.971, 2.084, 2.663, 4.764, 3.259],
    "dec": [None, 2.503, 3.993, 10.528, 5.386, 0.589, 1.302, 2.104, 2.973, 1.559, 0.202, 0.547, 2.034, 2.677, 4.197, 3.703]
}

df = pd.DataFrame(data)

In [2]:
quarters = {
    "Q1": ["jan", "feb", "mar"],
    "Q2": ["apr", "may", "jun"],
    "Q3": ["jul", "aug", "sep"],
    "Q4": ["oct", "nov", "dec"]
}

rows = []

for _, r in df.iterrows():
    for q, months in quarters.items():
        values = r[months].dropna()
        if len(values) == 0:
            continue

        rows.append({
            "Year": r["Year"],
            "Quarter": int(q[1]),
            "Period": f"{r['Year']} {q}",
            "Inflation_Rate": values.mean()
        })

inflation_q = pd.DataFrame(rows)

In [4]:
inflation_q.to_csv("uk_inflation_quarterly.csv", index=False)

In [9]:
ni_districts = [
    "Antrim and Newtownabbey",
    "Ards and North Down",
    "Armagh City, Banbridge and Craigavon",
    "Belfast",
    "Causeway Coast and Glens",
    "Derry City and Strabane",
    "Fermanagh and Omagh",
    "Lisburn and Castlereagh",
    "Mid and East Antrim",
    "Mid Ulster",
    "Newry, Mourne and Down"
]

In [10]:
all_q = pd.read_csv("quarterly_all_island.csv")

ni_q = all_q[all_q["County"].isin(ni_districts)].copy()
roi_q = all_q[~all_q["County"].isin(ni_districts)].copy()

ni_q.to_csv("ni_quarterly.csv", index=False)
roi_q.to_csv("roi_quarterly.csv", index=False)

In [12]:
uk_inf = pd.read_csv("uk_inflation_quarterly.csv")

ni_inf = ni_q.merge(
    uk_inf,
    on=["Year", "Quarter", "Period"],
    how="left"
)

ni_inf.head()

,County,Year,Quarter,Period,transaction_count,avg_price,Inflation_Rate
0,Antrim and Newtownabbey,2010,1,2010 Q1,217.0,148341.7353,NaN
1,Antrim and Newtownabbey,2010,2,2010 Q2,245.0,152846.0905,NaN
2,Antrim and Newtownabbey,2010,3,2010 Q3,269.0,156920.9890,NaN
3,Antrim and Newtownabbey,2010,4,2010 Q4,270.0,138840.4671,NaN
4,Antrim and Newtownabbey,2011,1,2011 Q1,205.0,134269.2020,NaN

In [13]:
uk_inf = pd.read_csv("uk_inflation_quarterly.csv")

print(uk_inf.head(10))
print(uk_inf.dtypes)

     Year  Quarter     Period  Inflation_Rate
0  2025.0        1  2025.0 Q1        2.804333
1  2025.0        2  2025.0 Q2        3.487000
2  2025.0        3  2025.0 Q3        3.800000
3  2025.0        4  2025.0 Q4        3.559000
4  2024.0        1  2024.0 Q1        3.540000
5  2024.0        2  2024.0 Q2        2.099333
6  2024.0        3  2024.0 Q3        2.043333
7  2024.0        4  2024.0 Q4        2.468667
8  2023.0        1  2023.0 Q1       10.175000
9  2023.0        2  2023.0 Q2        8.429667
Year              float64
Quarter             int64
Period             object
Inflation_Rate    float64
dtype: object

In [14]:
print(ni_q[["Year", "Quarter", "Period"]].head(10))
print(ni_q.dtypes)

   Year  Quarter   Period
0  2010        1  2010 Q1
1  2010        2  2010 Q2
2  2010        3  2010 Q3
3  2010        4  2010 Q4
4  2011        1  2011 Q1
5  2011        2  2011 Q2
6  2011        3  2011 Q3
7  2011        4  2011 Q4
8  2012        1  2012 Q1
9  2012        2  2012 Q2
County                object
Year                   int64
Quarter                int64
Period                object
transaction_count    float64
avg_price            float64
dtype: object

In [15]:
# Fix Year type
uk_inf["Year"] = uk_inf["Year"].astype(int)

# Rebuild Period cleanly
uk_inf["Period"] = (
    uk_inf["Year"].astype(str)
    + " Q"
    + uk_inf["Quarter"].astype(str)
)

In [16]:
print(uk_inf.head())
print(uk_inf.dtypes)

   Year  Quarter   Period  Inflation_Rate
0  2025        1  2025 Q1        2.804333
1  2025        2  2025 Q2        3.487000
2  2025        3  2025 Q3        3.800000
3  2025        4  2025 Q4        3.559000
4  2024        1  2024 Q1        3.540000
Year                int64
Quarter             int64
Period             object
Inflation_Rate    float64
dtype: object

In [17]:
ni_inf = ni_q.merge(
    uk_inf,
    on=["Year", "Quarter", "Period"],
    how="left"
)

In [18]:
ni_inf[["Year", "Quarter", "Period", "Inflation_Rate"]].head(10)

   Year  Quarter   Period  Inflation_Rate
0  2010        1  2010 Q1        3.275333
1  2010        2  2010 Q2        3.457667
2  2010        3  2010 Q3        3.085333
3  2010        4  2010 Q4        3.375333
4  2011        1  2011 Q1        4.118333
5  2011        2  2011 Q2        4.377333
6  2011        3  2011 Q3        4.705333
7  2011        4  2011 Q4        4.647667
8  2012        1  2012 Q1        3.490667
9  2012        2  2012 Q2        2.755333

In [19]:
ni_inf.head()

,County,Year,Quarter,Period,transaction_count,avg_price,Inflation_Rate
0,Antrim and Newtownabbey,2010,1,2010 Q1,217.0,148341.7353,3.275333
1,Antrim and Newtownabbey,2010,2,2010 Q2,245.0,152846.0905,3.457667
2,Antrim and Newtownabbey,2010,3,2010 Q3,269.0,156920.9890,3.085333
3,Antrim and Newtownabbey,2010,4,2010 Q4,270.0,138840.4671,3.375333
4,Antrim and Newtownabbey,2011,1,2011 Q1,205.0,134269.2020,4.118333

In [20]:
ni_inf.to_csv("ni_quarterly_inflation.csv", index=False)

In [33]:
ni_inf["avg_price"] = ni_inf["avg_price"].round(2)
ni_inf["Inflation_Rate"] = ni_inf["Inflation_Rate"].round(2)

In [34]:
ni_inf.to_csv("ni_quarterly_inflation.csv", index=False)

In [21]:
roi = pd.read_csv("roi_inflation_monthly.csv")

In [22]:
roi = roi[["Month", "VALUE"]].copy()
roi.rename(columns={"VALUE": "Inflation_Rate"}, inplace=True)

In [23]:
# Extract Year
roi["Year"] = roi["Month"].str.extract(r"(\d{4})").astype(int)

# Extract Month name
roi["Month_Name"] = roi["Month"].str.replace(r"\d{4}\s+", "", regex=True)

In [ ]:
# convert month names to numbers
month_map = {
    "January": 1, "February": 2, "March": 3,
    "April": 4, "May": 5, "June": 6,
    "July": 7, "August": 8, "September": 9,
    "October": 10, "November": 11, "December": 12
}

roi["Month_Num"] = roi["Month_Name"].map(month_map)

In [26]:
roi["Quarter"] = ((roi["Month_Num"] - 1) // 3 + 1).astype(int)

In [27]:
roi_q = (
    roi
    .groupby(["Year", "Quarter"])
    .agg(Inflation_Rate=("Inflation_Rate", "mean"))
    .reset_index()
)

In [28]:
roi_q["Period"] = (
    roi_q["Year"].astype(str) + " Q" + roi_q["Quarter"].astype(str)
)

In [30]:
roi_q = roi_q[["Year", "Quarter", "Period", "Inflation_Rate"]]
roi_q.head()

   Year  Quarter   Period  Inflation_Rate
0  2010        1  2010 Q1       -3.366667
1  2010        2  2010 Q2       -1.333333
2  2010        3  2010 Q3        0.200000
3  2010        4  2010 Q4        0.933333
4  2011        1  2011 Q1        2.266667

In [31]:
roi_q["Inflation_Rate"] = roi_q["Inflation_Rate"].round(2)

In [32]:
roi_q.to_csv("roi_inflation_quarterly.csv", index=False)

In [36]:
ni_inf["real_avg_price"] = (
    ni_inf["avg_price"] /
    (1 + ni_inf["Inflation_Rate"] / 100)
).round(2)

In [37]:
missing = ni_inf["Inflation_Rate"].isna().mean()
print(f"Missing inflation rate: {missing:.2%}")

Missing inflation rate: 0.00%

In [38]:
ni_inf["avg_price"] = ni_inf["avg_price"].round(2)
ni_inf["Inflation_Rate"] = ni_inf["Inflation_Rate"].round(2)

In [39]:
ni_inf.to_csv("ni_quarterly_inflation.csv", index=False)